### ISSUE TITLE
Issue with the files for project 

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Archive/pride-archive-api#60]
````
https://www.ebi.ac.uk/pride/ws/archive/v2/files/PXD003180
```

Error: 

```
Servlet.service() for servlet [dispatcherServlet] in context with path [/pride/ws/archive/v2] threw exception [Request processing failed; nested exception is java.util.NoSuchElementException: No value present] with root cause

java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135) ~[na:1.8.0_151]
	at uk.ac.ebi.pride.ws.pride.controllers.file.FileController.getFile(FileController.java:89) ~[classes!/:1.0.0-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
```

**Comment by chakrabandla** [comment]
This endpoint is to get by fileAccession not projectAccession..
